import React from 'react'
import { Button } from './ui/button'
import HomeSlider from './slider/Herosectionslider'
import HearoHomeSlider from './slider/Herosectionslider'
import Link from 'next/link'

function HearoSection() {
  return (
      <section className="w-full lg:flex lg:justify-center max-h-[500px] py-10 bg-gradient-to-r from-white to-[#c7b8e0] ">
      <div className="w-[100%] 2xl:w-[1200px] ">
        <div className="w-full px-6 py-4 flex lg:justify-center ">
        <div className='md:w-[50%] lg:w-[40%] w-full relative flex flex-col justify-center'>
          <h3 className='lg:text-[36px] text-[30px]  text-[#0061F2] font-bold w-fit' >IMPRESSIVE RESUMES</h3>
          <h3 className='write-animation  lg:text-[36px] text-[30px] font-semibold  absolute lg:top-[33px] md:top-9 top-7     text-[#334155]' style={{animationDelay:'0.5s'}}>EASY ONLINE BUILDER</h3>
          <p className='md:mt-12 mt-7 w-[370px]'>Professional out-of-the-box resumes, instantly generated by the most advanced resume builder technology available.</p>
         <span className='flex gap-x-2 mt-5'>
          <Link href={`choesoptions`}>
           <Button className='text-white  bg-gradient-to-r from-[#334155] to-[#0061F2]   cursor-pointer shadow-sm transition-all hover:scale-105 hover:bg-white'>Build resume</Button>
          </Link>
          <Link href={`upload`}>
          <Button className='bg-white  hover:bg-gradient-to-r from-[#334155] to-[#0061F2] text-[#334155] hover:text-white cursor-pointer shadow-sm transition-all hover:scale-105'>Upload resume</Button>
          </Link>
         </span>
        </div>
        <div className='lg:w-[40%] md:w-[50%] hidden md:block'>
          <HearoHomeSlider/>
        </div>
        </div>
      </div>
    </section>
  )
}

export default HearoSection